### ISSUE TITLE
Al cambiar de dimension es posible quedar softblockeado

### ISSUE THREAD

**Issue by Kevadroz** [HelldogPack/JoyMix-modpack#5]
Cuando un jugador cambia de una dimension a otra es posible que dicho jugador quede en un estado "fantasma", la entidad no se renderiza, no se puede mover y F3+F4 no funciona alegando que el usuario no tiene permisos, aunque los comandos via chat siguen funcionando sin problema.

Se puede solucionar volviendo a unirse al mundo.

Probado solo en solitario.

**Comment by FOREVEREALIZE** [comment]
Esto ocurre con transiciones entre dos dimensiones especificas o con cualquieras dos dimensiones?
Con que version de JoyMix ocurre?

**Comment by Kevadroz** [comment]
> Esto ocurre con transiciones entre dos dimensiones especificas o con cualquieras dos dimensiones? Con que version de JoyMix ocurre?

Pasa en cualquier dimension (que yo sepa), y en cualquier versión (en el caso de la 1.0, Immersive portals lo evita al usar sus portales)

**Comment by FOREVEREALIZE** [comment]
No se ha podido replicar.

**Comment by Kevadroz** [comment]
> No se ha podido replicar.

Que has intentado? A mí me pasa con los portales del nether por ejemplo, a veces.

**Comment by FOREVEREALIZE** [comment]
Estuve 3 horas pasando del nether al overworld y de vuelta y nada

**Comment by Kevadroz** [comment]
Wtf a mí me pasa la mitad de las veces. Hay una variable que se nos está pasando

**Comment by FOREVEREALIZE** [comment]
Ciertamente

**Comment by FOREVEREALIZE** [comment]
El origen problema ha sido identificado y se cree que la causa son: `Charm`, `Infinite Music` o `Music Duration Reducer` (o una combinacion de los anteriores). Tambien parece que solo ocurre en ciertos sistemas.

Seguimos trabajando en buscar una solución.

**Comment by Kevadroz** [comment]
La solución planeada es la eliminación de Music Duration Reducer
