### ISSUE TITLE
[Bug]: Materiales de SIlent Gear no Cargan

### ISSUE THREAD

**Issue by FOREVEREALIZE** [HelldogPack/JoyMix-modpack#8]
### Que ha pasado?

Al abrir un mundo, Silent Gear ha informado de que los materiales `helldogpack:aeternium`, `helldogpack:terminite` y `helldogpack:thallasium` no han cargado correctamente

### Que esperabas que pasara?

Que todos los materiales carguen correctamente

### Versión

Otra (Por favor pon tu version de JoyMix en los comentarios)

### En que sistemas operativos estas encontrando el problema?

Windows

### Que versión de java estás usando?

Java 8

### Archivo de log

https://gist.github.com/FOREVEREALIZE/00a8cb6f0875353bdcaa93aa08764a63

### Archivo de debugging

_Inexistente_

### Comentarios

Version de JoyMix: Commit b596f30

**Comment by Kevadroz** [comment]
Estas usando BetterEnd Forge o BetterEnd ReForked?

**Comment by FOREVEREALIZE** [comment]
El que este en el Commit que he puesto. Es el modpack original de ese commit

**Comment by FOREVEREALIZE** [comment]
Me acabo de dar cuenta que b596f30 no incluye ninguna version de BetterEnd o BetterEnd Reforked

**Comment by Kevadroz** [comment]
@FOREVEREALIZE Comprueba el ultimo commit cuando puedas

**Comment by FOREVEREALIZE** [comment]
Puedo confirmar que parece que ya no ocurre en el commit 4e63beb
